version: '1'
services:
  app:
    build:
      context: .
      dockerfile: 
       Dockerfile
    hostname: 
      knowledge-base
    image:
      t-base2204

    ports:
      - 5902:5900
      - 6902:80
      - 4902:22
      - 8888:8888

    restart: always 
    volumes:
      - type: volume
        source: nfs-volume 
        target: /root/Desktop/nfs
        volume:
          nocopy: true

volumes:
  nfs-volume :
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.10.250,nolock,soft,rw
      device: ":/volume1/成員共享空間/bruce/知識庫"